import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Bar from "@/components/bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Zohaib-Porfolio",
  description: "Generated by Portfolio",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="max-sm:flex max-md:flex-col md:min-h-[100vh]  flex lg:min-h-[100vh] xl:min-h-[100vh] 2xl:min-h-[100vh] lg:flex xl:flex 2xl:flex">
          <div className="max-sm:hidden sm:hidden max-md:hidden md:block lg:block xl:block 2xl:block">
            <Navbar />
          </div>
          <div className="max-sm:block sm:block max-md:block md:hidden lg:hidden xl:hiddden 2xl:hidden">
            <Bar />
          </div>
          <main className="sm:w-full sm:p-7 max-md:w-full max-md:p-7 flex flex-col p-10 grow">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
