import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Bar from "@/components/bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Zohaib-Porfolio",
  description: "Generated by Portfolio",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex-col md:flex-row min-h-[100vh] flex">
          <div className="hidden md:block">
            <Navbar />
          </div>
          <main className="w-full p-7 flex flex-col md:p-10 grow">
            {children}
          </main>
          <div className="block md:hidden sticky bottom-0">
            <Bar />
          </div>
        </div>
      </body>
    </html>
  );
}
